export enum Feature {
    PROPERTIES_CREATE = 'PROPERTIES_CREATE',
    PROPERTIES_UNLIMITED = 'PROPERTIES_UNLIMITED',
    PROPERTY_GALLERY = 'PROPERTY_GALLERY',
    PUBLIC_PROPERTY_PAGE = 'PUBLIC_PROPERTY_PAGE',
    TENANTS = 'TENANTS',
    TENANT_RATING = 'TENANT_RATING',
    CONTRACTS = 'CONTRACTS',
    CONTRACTS_PDF = 'CONTRACTS_PDF',
    DIGITAL_SIGNATURE = 'DIGITAL_SIGNATURE',
    FINANCIAL = 'FINANCIAL',
    RECEIPTS = 'RECEIPTS',
    REPORTS_BASIC = 'REPORTS_BASIC',
    REPORTS_ADVANCED = 'REPORTS_ADVANCED',
    AGENDA = 'AGENDA',
    HELPDESK = 'HELPDESK',
    DOCUMENT_VAULT = 'DOCUMENT_VAULT',
    WHATSAPP = 'WHATSAPP',
    WHATSAPP_API = 'WHATSAPP_API',
    EMAIL = 'EMAIL',
    MARKETPLACE = 'MARKETPLACE',
    MERCADO_PAGO = 'MERCADO_PAGO',
    PIX = 'PIX',
    BANK_RECONCILIATION = 'BANK_RECONCILIATION',
    NOTIFICATIONS = 'NOTIFICATIONS',
    API_ACCESS = 'API_ACCESS',
    ARGUS = 'ARGUS',
    BACKUP = 'BACKUP',
    EXPORT_DATA = 'EXPORT_DATA',
    MULTI_USER = 'MULTI_USER',
    CUSTOM_BRANDING = 'CUSTOM_BRANDING'
}

export enum LimitType {
    PROPERTY_LIMIT = 'PROPERTY_LIMIT',
    TENANT_LIMIT = 'TENANT_LIMIT',
    CONTRACT_LIMIT = 'CONTRACT_LIMIT',
    DOCUMENT_LIMIT = 'DOCUMENT_LIMIT',
    STORAGE_LIMIT = 'STORAGE_LIMIT',
    USER_LIMIT = 'USER_LIMIT'
}

export interface PlanFeature {
    feature: string;
    enabled: boolean;
}

export interface PlanLimit {
    feature: string;
    max_limit: number;
}
