import React, { useState, useEffect } from 'react';
import { supabase } from '../lib/supabase';
import { useAuth } from '../contexts/AuthContext';
import { Bell, X } from 'lucide-react';
import { motion, AnimatePresence } from 'motion/react';

// For a real production app, you need a VAPID public key generated by your server
// To generate: npx web-push generate-vapid-keys
const PUBLIC_VAPID_KEY = 'BEl62iUYgUivxIkv69yViEuiBIa-Ib9-SkvMeAtA3LFgDzkrxZJjSgSnfckjBJuB-5WQDPtAdjfGz0-6a-O7G8g'; // Example/Placeholder

function urlBase64ToUint8Array(base64String: string) {
    const padding = '='.repeat((4 - base64String.length % 4) % 4);
    const base64 = (base64String + padding)
        .replace(/\-/g, '+')
        .replace(/_/g, '/');

    const rawData = window.atob(base64);
    const outputArray = new Uint8Array(rawData.length);

    for (let i = 0; i < rawData.length; ++i) {
        outputArray[i] = rawData.charCodeAt(i);
    }
    return outputArray;
}

export default function PWAPrompt() {
    const { user } = useAuth();
    const [showPrompt, setShowPrompt] = useState(false);

    useEffect(() => {
        // Only show if we're in a browser that supports service workers and notifications
        if (!('serviceWorker' in navigator) || !('PushManager' in window)) {
            return;
        }

        if (Notification.permission === 'default' && user) {
            // Delay prompt to not annoy user immediately on load
            const timer = setTimeout(() => setShowPrompt(true), 3000);
            return () => clearTimeout(timer);
        }
    }, [user]);

    const handleSubscribe = async () => {
        try {
            const permission = await Notification.requestPermission();

            if (permission === 'granted') {
                const registration = await navigator.serviceWorker.ready;

                try {
                    const subscription = await registration.pushManager.subscribe({
                        userVisibleOnly: true,
                        applicationServerKey: urlBase64ToUint8Array(PUBLIC_VAPID_KEY)
                    });

                    if (user?.uid) {
                        await supabase.from('profiles').update({
                            push_subscription: JSON.parse(JSON.stringify(subscription))
                        }).eq('id', user.uid);
                        console.log('✅ Inscrição Push salva no Supabase.');
                    }
                } catch (e) {
                    console.error('Push auth falhou. Requer VAPID key real:', e);
                    // Fallback just granting permission locally
                    alert('Notificações ativadas no navegador!');
                }
            }
        } catch (err) {
            console.error(err);
        } finally {
            setShowPrompt(false);
        }
    };

    const handleDismiss = () => {
        setShowPrompt(false);
    };

    return (
        <AnimatePresence>
            {showPrompt && (
                <motion.div
                    initial={{ opacity: 0, y: 50 }}
                    animate={{ opacity: 1, y: 0 }}
                    exit={{ opacity: 0, scale: 0.9, y: 20 }}
                    className="fixed bottom-6 right-6 sm:bottom-10 sm:right-10 z-[100] bg-white dark:bg-slate-900 border border-slate-200 dark:border-slate-800 rounded-3xl p-5 shadow-2xl flex max-w-sm w-[calc(100%-2rem)] mx-auto md:mx-0"
                >
                    <div className="flex-1 mr-4">
                        <div className="flex items-center gap-3 mb-2">
                            <div className="w-10 h-10 rounded-full bg-blue-100 flex items-center justify-center text-blue-600">
                                <Bell size={20} />
                            </div>
                            <h4 className="font-bold text-slate-800 dark:text-white">Ativar Notificações?</h4>
                        </div>
                        <p className="text-sm text-slate-500 mb-4">
                            Receba alertas de novos aluguéis, vencimentos e chamados de manutenção.
                        </p>
                        <div className="flex gap-2">
                            <button
                                onClick={handleSubscribe}
                                className="flex-1 bg-primary text-white text-sm font-bold py-2 px-4 rounded-xl hover:bg-primary/90"
                            >
                                Permitir
                            </button>
                        </div>
                    </div>
                    <button
                        onClick={handleDismiss}
                        className="absolute top-4 right-4 text-slate-400 hover:text-slate-600 p-1"
                    >
                        <X size={16} />
                    </button>
                </motion.div>
            )}
        </AnimatePresence>
    );
}
